### ISSUE TITLE
Getting http://example.com/operations crashes

### ISSUE THREAD

**Issue by raumaankidwai** [raumaankidwai/nim#1]
server.js crashed due to `fs` uncaught error in `Nim.NimServer.processURI`

```
Tests succeeded!
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir ''
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Server.processURI (/home/pi/nim/nim.js:90:19)
    at Server.process.e (/home/pi/nim/nim.js:30:18)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

Log from `lynx`:

```
Looking up  '' first

Looking up example.com first
Looking up example.com
Making HTTP connection to example.com
Sending HTTP request.
HTTP request sent; waiting for response.
Alert!: Unexpected network read error; connection aborted.
Can't Access `http://example.com/operations'
Alert!: Unable to access document.

lynx: Can't access startfile
```

**Comment by raumaankidwai** [comment]
**raumaankidwai** goes to sleep just now

**Comment by raumaankidwai** [comment]
Closed, fixed on my local repo and so fix will be committed next along with a bunch of other awesome stuff :D
